name: lint

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  php-lint:
    name: Lint PHP

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint PHP files
        uses: overtrue/phplint@main
        with:
          path: .
          options: --exclude=vendor

      - name: Set PHP Lint Status Check
        run: echo ::set-output name=lint_result_php::success

  assets-lint:
    name: Lint Assets with Stylelint and ESLint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Node.js Dependencies
        run: cd ./www/wordpress/themes/eteczonaleste && npm install

      - name: Run JS Lint
        run: cd ./www/wordpress/themes/eteczonaleste && npm run lint:js

      - name: Set JS Lint Status Check
        run: echo ::set-output name=lint_result_js::success

      - name: Run CSS Lint
        run: cd ./www/wordpress/themes/eteczonaleste && npm run lint:css

      - name: Set CSS Lint Status Check
        run: echo ::set-output name=lint_result_css::success

  approvals:
    name: Check Linting Results
    runs-on: ubuntu-latest
    needs:
      - php-lint
      - assets-lint

    steps:
      - name: Check PHP Lint Result
        run: echo "PHP Lint Result ${{needs.php-lint.outputs.lint_result_php}}"

      - name: Check Lint JS Result
        run: echo "Assets Lint Result JS ${{needs.assets-lint.outputs.lint_result_js}}"

      - name: Check Lint CSS Result
        run: echo "Assets Lint Result CSS ${{needs.assets-lint.outputs.lint_result_css}}"

